CREATE TABLE FOO_USER
(
   ID bigint PRIMARY KEY,
   EMAIL varchar(255),
   USERNAME varchar(100),
   NAME varchar(100),
   PASSWORD varchar(255),
   COMPANY_ID bigint
);

CREATE TABLE FOO_USER_COMPANY
(
   USER_ID bigint,
   ASSIGNED_COMPANY bigint,
   CONSTRAINT PK_FOO_USER_COMPANY PRIMARY KEY (USER_ID,ASSIGNED_COMPANY)
);

CREATE TABLE FOO_COMPANY
(
   ID bigint PRIMARY KEY,
   SUPPLIER char(1),
   NAME varchar(100)
);

CREATE TABLE FOO_ROLE
(
   ID bigint PRIMARY KEY,
   FIXED_ROLE char(1),
   ROLE_NAME varchar(100)
);

CREATE TABLE FOO_DATA
(
   ID bigint PRIMARY KEY,
   SOME_DATA BLOB(10000)
);

ALTER TABLE FOO_USER
ADD CONSTRAINT FK_FOO_COMPANY
FOREIGN KEY (COMPANY_ID)
REFERENCES FOO_COMPANY(ID);

CREATE UNIQUE INDEX FOO_USER_IDX ON FOO_USER(ID);

CREATE INDEX COMPANY_IDX ON FOO_USER(COMPANY_ID);

CREATE UNIQUE INDEX USERNAME_IDX ON FOO_USER(USERNAME);

CREATE UNIQUE INDEX FOO_ROLE_NAME ON FOO_ROLE(ROLE_NAME);