CREATE TABLE "FOO USER"
(
   ID bigint PRIMARY KEY,
   PERSONAL_NUMBER BIGINT,
   USERNAME varchar(100),
   NAME varchar(100),
   PASSWORD varchar(255),
   COMPANY_ID bigint
);

CREATE TABLE "FOO USER COMPANY"
(
   USER_ID bigint,
   ASSIGNED_COMPANY_ID bigint,
   CONSTRAINT PK_FOO_USER_COMPANY PRIMARY KEY (USER_ID, ASSIGNED_COMPANY_ID)
);
